#!/usr/bin/env bash
is_mounted=false

if mount | grep -qs "on /efi"; then
  echo -e "ESP is mounted.\n"
  echo "Type <u> to unmount; Enter to quit. "
  is_mounted=true

else
  echo -e "ESP is not mounted.\n"
  echo -e "It is safe to turn on the Virtual Machine.\n"
  echo "Type <m> to mount; Enter to quit. "
fi

read choice

if [[ $choice == "u" ]] && [[ "$is_mounted" == true ]]; then
  if sudo umount /dev/disk/by-label/ESP; then
    echo -e "\n"
    echo "ESP unmounted."
    sleep 0.4
  fi

elif [[ $choice == "m" ]] && [[ "$is_mounted" == false ]]; then
  if sudo mount /dev/disk/by-label/ESP; then
    echo -e "\n"
    echo "ESP mounted."
    sleep 0.4
  fi

fi
